language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/*/*.ino

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno --board=megaatmega2560